## 统一错误返回格式

```python
from fastapi.exceptions import RequestValidationError
from fastapi import Request, HTTPException
from fastapi.responses import JSONResponse
import traceback

# 参数校验错误
@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    print("[Validation Error]", exc)
    error_messages = []
    for err in exc.errors():
        # 去掉 body 前缀
        loc = ".".join(str(part) for part in err["loc"])
        msg = "参数 " + loc + " 缺失"
        error_messages.append(msg)

    full_msg = "；".join(error_messages)
    return response(422, f"参数校验失败：{ full_msg }", {"detail": exc.errors()})

# raise HTTPException 异常
@app.exception_handler(HTTPException)
async def custom_http_exception_handler(request: Request, exc: HTTPException):
    return response(exc.status_code, exc.detail)

# 所有其他未处理异常
@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    print("[Unhandled Exception]", traceback.format_exc())
    return response(500, "服务器内部错误")
```

- utils.py

```python
def response(code: int, msg: str, data=None):
    return JSONResponse(
        status_code=200,
        content={
            "code": code,  # 200表示成功, 201表示失败, 301表示没有权限
            "data": data or [],
            "msg": msg,
        },
    )
```

